#################################### Common Configurations##############################
common:
    version: 0.1.0
    log_level: debug
    is_prod: false
    app_name: "aiapm"

#################################### Server ##############################
server:
    addr: ":10086"
    base_url: "/api"

#################################### User/Session ##############################
user: 
    # a session is created when user login to im.dev, this session will be expired after X seconds
    session_expire: 259200


#################################### Paths ##############################
# Path to where im.dev can store temp files, sessions, and the sqlite3 db (if that is used)
paths:
    # sqlite3 db files
    data: ""
    logs: ""



#################################### Datasource ##############################
datasource:
   prometheus_addr: http://localhost:9090
   jaeger_addr: 
   external_http_addr: 

#################################### SMTP ##############################
smtp:
  addr: ""
  from_address: ""
  from_name: ""
  auth_username: "" 
  auth_password: ""
