#################################### Common Configurations##############################
common:
    version: 0.7.0-dev
    log_level: info
    is_prod: false
    app_name: "datav"
    repo_url: "https://github.com/DataObserve/datav" # leaving empty will hide the github icon in sidemenu

#################################### Server ##############################
server:
    addr: ":8080"
    base_url: "/api/test"

#################################### Database ##############################
database:
    connect_to: mysql
    account: root
    account_secret: Sunface-Mysql-im.dev
    host: localhost
    port: 3306
    database: test

#################################### User/Session ##############################
user: 
    # a session is created when user login to im.dev, this session will be expired after X seconds
    # default is 1 month
    session_expire: 2592000

    # when enabled, various users can login with the same account name
    enable_multi_login: false

#################################### Paths ##############################
# Path to where im.dev can store temp files, sessions, and the sqlite3 db (if that is used)
paths:
    # sqlite3 db files
    data: ""
    logs: ""

#################################### Dashboard  ##############################
dashboard: 
    enable_delete: true

#################################### Clean Tasks  ##############################
task: 
    # annotations created longer than this will be auto deleted
    # default is 90 days
    clean_annotations: 90

#################################### Datasource Plugins ##############################
datasource:
   prometheus_addr: http://localhost:9090
   jaeger_addr: 
   external_http_addr: 

#################################### Panel Plugins ##############################
panel:
  echarts: 
    enable_baidu_map: false
    baidu_map_ak: "" # apply at https://lbsyun.baidu.com/apiconsole/center#/home

#################################### SMTP ##############################
smtp:
  addr: ""
  from_address: ""
  from_name: ""
  auth_username: "" 
  auth_password: ""


#################################### Paths ##############################
# Path to where datav can store temp files, sessions, and the sqlite3 db (if that is used)
paths:
    # sqlite3 db files
    sqlite_data: ""
    logs: ""

#################################### Sidemenu ##############################
sidemenu:
    show_alert_icon: true