version: "2.4"

services:
  query:
    container_name: datav-query
    build:
      context: "../query"
      dockerfile: "./Dockerfile"
      args:
        LDFLAGS: ""
        TARGETPLATFORM: "${GOOS}/${GOARCH}"
    volumes:
      - ../query/data/:/var/lib/xobserve/
      - ../query/xobserve.yaml:/etc/xobserve/xobserve.yaml
    command: []
    ports:
      - "10086:10086"
    restart: on-failure

  frontend:
    container_name: datav-frontend
    build:
      context: "../frontend"
      dockerfile: "./Dockerfile"
      args:
        TARGETOS: "${GOOS}"
        TARGETPLATFORM: "${GOARCH}"
    environment:
      - QUERY_SERVICE_ADDR=http://host.docker.internal:10086
    restart: on-failure
    depends_on:
      - query
    ports:
      - "5173:5173"
