version: "2.4"

services:
  query:
    container_name: datav-query
    hostname: datav-query
    build:
      context: "../datav/query"
      dockerfile: "./Dockerfile"
      args:
        LDFLAGS: ""
        TARGETPLATFORM: "${GOOS}/${GOARCH}"
    volumes:
      - ./data/xobserve/:/var/lib/datav/
      - ../datav/query/datav.yaml:/etc/datav/datav.yaml
    command: []
    ports:
      - "10086:10086"
    restart: on-failure

  frontend:
    container_name: datav-frontend
    build:
      context: "../datav/frontend"
      dockerfile: "./Dockerfile"
      args:
        TARGETOS: "${GOOS}"
        TARGETPLATFORM: "${GOARCH}"
    environment:
      - QUERY_SERVICE_ADDR=http://datav-query:10086
    restart: on-failure
    depends_on:
      - query
    ports:
      - "5173:5173"
